# Site settings
title: My Blog
email: kf.two.two@gmail.com
description: >
  My Personal Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kftwotwo.github.io" # the base hostname & protocol for your site
twitter_username: kftwotwo
github_username:  kftwotwo

# Build settings
markdown: kramdown
